"""Generating VS Code run/debug configuration for a puzzle/contribution working directory.

   A language plugin describes *what* it needs (`CgLanguage.build_vscode_provisioning` ->
   `CgVsCodeProvisioning`); this module owns *where it goes* and *how it merges* with whatever the
   user already has. Sibling of `_process.py`/`_docker.py`--deliberately outside `languages/`, so
   the registry's discovery walk never sees it.

   Two things here are less obvious than they look:

   **VS Code only reads `.vscode/launch.json` from the workspace root folder**, never from a
   subdirectory. A puzzle working directory is very often a subdirectory of the user's real
   workspace (this repo's own `puzzle/` and `contribution/` are exactly that), so writing
   `<root>/.vscode/launch.json` would be silently ignored. Everything therefore targets a
   *resolved workspace root* (see `find_workspace_root`), and every generated path that refers to
   the working directory is **absolute**--`${workspaceFolder}` is the wrong answer whenever the
   workspace root isn't the working directory, which is the common case.

   **`launch.json`/`tasks.json` are JSONC**, not JSON: VS Code allows `//` comments and trailing
   commas, and plenty of real files use them. `json.loads` raises on those, so rather than risk
   corrupting a hand-edited file this module refuses to merge into anything it can't parse strictly
   (see `CgVsCodeMergeError`) unless explicitly told to overwrite.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

__all__ = [
    "CgLaunchTestCase",
    "CgVsCodeKind",
    "CgVsCodeRequest",
    "CgVsCodeProvisioning",
    "CgVsCodeMergeError",
    "find_workspace_root",
    "owner_name",
    "owner_slug",
    "write_provisioning",
]

CgVsCodeKind = Literal["puzzle", "contribution"]

_WORKSPACE_MARKER_DIRS = (".vscode", ".git", ".hg", ".svn")

_LAUNCH_FILE_NAME = "launch.json"
_TASKS_FILE_NAME = "tasks.json"
_EXTENSIONS_FILE_NAME = "extensions.json"
_VSCODE_DIR_NAME = ".vscode"


@dataclass(frozen=True)
class CgLaunchTestCase:
    """One selectable test case, for the `pickString` dropdown a debug configuration offers.

       Deliberately minimal and kind-agnostic: `id` is whatever token the corresponding
       `python -m ...debug` entry point expects (a puzzle's 1-based index, a contribution's
       ordinal), and the plugin decides how to present it. A contribution's local/validator *side*
       is not modeled here--it's a fixed two-value choice the plugin emits as its own input, rather
       than multiplying every ordinal by two in one list."""

    id: str
    label: str


@dataclass(frozen=True)
class CgVsCodeRequest:
    """What a language plugin is being asked to generate configuration for."""

    ctx: Any
    """The `CgLanguageContext` for the working directory (typed loosely to avoid a circular import
       with `base`--see `codingame_tools.language.base.CgLanguageContext`)."""

    kind: CgVsCodeKind
    """Whether this is a puzzle or a contribution working directory. Determines which
       `python -m ...debug` entry point and which argument shape a config needs, so plugins that
       generate debug configs must branch on it."""

    test_cases: tuple[CgLaunchTestCase, ...]
    """Every test case currently on disk, in display order--generated fresh so a `pickString` list
       never goes stale (the hand-maintained lists this replaces had to be regenerated by hand)."""

    workspace_root: Path
    """Where `.vscode/` will be written--see `find_workspace_root`. Often *not* `ctx.root`."""


@dataclass(frozen=True)
class CgVsCodeProvisioning:
    """What a language plugin wants written. Everything is optional--a plugin supplies only the
       pieces it actually has."""

    configurations: list[dict[str, Any]] = field(default_factory=list)
    """Entries for `launch.json`'s `configurations`. Each `name` must start with this working
       directory's owner prefix (see `owner_name`) so re-provisioning replaces exactly its own
       entries and leaves the user's--and other working directories'--alone."""

    inputs: list[dict[str, Any]] = field(default_factory=list)
    """Entries for `launch.json`'s `inputs`. Each `id` must start with this working directory's
       owner slug (see `owner_slug`), for the same reason."""

    tasks: list[dict[str, Any]] = field(default_factory=list)
    """Entries for `tasks.json`'s `tasks`. Each `label` must start with the owner prefix."""

    files: dict[str, str] = field(default_factory=dict)
    """Extra files to write, keyed by path **relative to the working directory root** (not the
       workspace root)--e.g. `.devcontainer/devcontainer.json`. Never `data/...`: that's a
       contribution's git work tree, where a generated file would be either committed into the
       server tree by `git add -A` or deleted by `git clean -fd`."""

    recommended_extensions: list[str] = field(default_factory=list)
    """Extension IDs to merge into `extensions.json`'s `recommendations` (union, never removing the
       user's own--there's no reliable way to tell which ones cg previously added)."""


class CgVsCodeMergeError(Exception):
    """Raised when an existing VS Code config file can't be safely merged into--almost always
       because it's JSONC (comments/trailing commas) rather than strict JSON. Refusing is
       deliberate: silently rewriting would drop the user's comments and any content our parser
       didn't understand."""


def find_workspace_root(root: Path) -> Path:
    """Best guess at the VS Code workspace root folder that contains `root`.

       Walks up from `root` looking for a directory that already has `.vscode/`, then for a VCS
       marker (`.git`/`.hg`/`.svn`), stopping at the filesystem root. Falls back to `root` itself,
       which is correct when the user opens the working directory directly as their folder.

       This matters because VS Code reads `launch.json` only from the workspace root--see the
       module docstring."""
    root = root.resolve()
    candidates = [root, *root.parents]
    for marker in _WORKSPACE_MARKER_DIRS:
        for candidate in candidates:
            if (candidate / marker).is_dir():
                return candidate
    return root


def owner_slug(root: Path) -> str:
    """A filesystem-safe identifier for the working directory that owns a generated entry, derived
       from its directory name (e.g. `puzzle`, `my-contribution` -> `my_contribution`).

       Used to scope re-provisioning: one workspace can contain several working directories (this
       repo has both a `puzzle/` and a `contribution/`), and provisioning one must not delete the
       other's entries. Two working directories with the *same* directory name in one workspace
       would collide--an accepted edge case, since the fix is simply to name them differently."""
    slug = re.sub(r"[^0-9A-Za-z]+", "_", root.name).strip("_")
    return slug or "cg"


def owner_name(root: Path) -> str:
    """Human-facing prefix for every generated `launch.json` configuration name / `tasks.json`
       label belonging to `root`, e.g. `"CG puzzle: "`. See `owner_slug` for why it's per-directory."""
    return f"CG {root.name}: "


def _read_json_object(path: Path, *, force: bool) -> dict[str, Any]:
    """Existing config as a dict, `{}` if absent. Raises `CgVsCodeMergeError` if present but not
       strict JSON, unless `force` (in which case it's discarded and overwritten)."""
    if not path.is_file():
        return {}
    text = path.read_text(encoding="utf-8")
    if not text.strip():
        return {}
    try:
        loaded = json.loads(text)
    except json.JSONDecodeError as e:
        if force:
            return {}
        raise CgVsCodeMergeError(
                f"{path} isn't strict JSON ({e})--VS Code allows comments and trailing commas "
                "there, but merging into such a file would silently drop them. Re-run with "
                "--force to overwrite it, or remove the comments first."
            ) from e
    if not isinstance(loaded, dict):
        if force:
            return {}
        raise CgVsCodeMergeError(f"{path} doesn't contain a JSON object at the top level.")
    return loaded


def _merge_by_key(
            existing: list[Any], generated: list[dict[str, Any]], *, key: str, prefix: str,
        ) -> list[dict[str, Any]]:
    """Replace exactly the entries this working directory owns (those whose `key` starts with
       `prefix`), preserving everything else in its original order, then append the generated
       ones."""
    kept = [
            e for e in existing
            if not (isinstance(e, dict) and isinstance(e.get(key), str) and e[key].startswith(prefix))
        ]
    return [*kept, *generated]


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def write_provisioning(
            provisioning: CgVsCodeProvisioning,
            *,
            root: Path,
            workspace_root: Path,
            force: bool = False,
        ) -> list[Path]:
    """Write `provisioning` into `<workspace_root>/.vscode/` (and `provisioning.files` into
       `root`), merging with whatever is already there.

    Args:
        provisioning:    What the language plugin produced.
        root:            The working directory root--owns the entry prefixes, and the base for
                          `provisioning.files`.
        workspace_root:  Where `.vscode/` lives--see `find_workspace_root`.
        force:           Overwrite an existing config file that isn't strict JSON instead of
                          refusing.

    Returns:
        Every path written, in write order.

    Raises:
        CgVsCodeMergeError: if an existing file can't be parsed and `force` is False.
    """
    written: list[Path] = []
    vscode_dir = workspace_root / _VSCODE_DIR_NAME
    name_prefix = owner_name(root)
    input_prefix = f"cg_{owner_slug(root)}_"

    if provisioning.configurations or provisioning.inputs:
        path = vscode_dir / _LAUNCH_FILE_NAME
        data = _read_json_object(path, force=force)
        data.setdefault("version", "0.2.0")
        data["inputs"] = _merge_by_key(
                data.get("inputs") or [], provisioning.inputs, key="id", prefix=input_prefix)
        data["configurations"] = _merge_by_key(
                data.get("configurations") or [], provisioning.configurations,
                key="name", prefix=name_prefix)
        _write_json(path, data)
        written.append(path)

    if provisioning.tasks:
        path = vscode_dir / _TASKS_FILE_NAME
        data = _read_json_object(path, force=force)
        data.setdefault("version", "2.0.0")
        data["tasks"] = _merge_by_key(
                data.get("tasks") or [], provisioning.tasks, key="label", prefix=name_prefix)
        _write_json(path, data)
        written.append(path)

    if provisioning.recommended_extensions:
        path = vscode_dir / _EXTENSIONS_FILE_NAME
        data = _read_json_object(path, force=force)
        # Union rather than replace: there's no marker distinguishing recommendations cg added
        # previously from ones the user added, so removing any would eventually delete theirs.
        existing = [e for e in (data.get("recommendations") or []) if isinstance(e, str)]
        data["recommendations"] = existing + [
                e for e in provisioning.recommended_extensions if e not in existing]
        _write_json(path, data)
        written.append(path)

    for relative, content in provisioning.files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)

    return written
